export function getRandomName() {
    return FAKE_NAMES[Math.floor(Math.random() * FAKE_NAMES.length)]
}

const FAKE_NAMES = [
    "Tonyrex",
    "IHasChins",
    "Tony",
    "Friendly",
    "Chins",
    "Tonyasaurus",
    "Rex",
    "Tony",
    "Gracious",
    "Arms",
    "Tony",
    "Australian",
    "Uber",
    "Rat",
    "Iamfriendly",
    "DrFluffy",
    "Gamerpuppy",
    "Aspect",
    "Kraken",
    "Bender",
    "Lynch",
    "Big Papa",
    "Mad Dog",
    "Bowser",
    "Bruise",
    "Psycho",
    "Cannon",
    "Ranger",
    "Clink",
    "Ratchet",
    "Cobra",
    "Reaper",
    "Colt",
    "Rigs",
    "Crank",
    "Ripley",
    "Creep",
    "Roadkill",
    "Daemon",
    "Ronin",
    "Decay",
    "Rubble",
    "Diablo",
    "Sasquatch",
    "Doom",
    "Scar",
    "Dracula",
    "Shiver",
    "Dragon",
    "Skinner",
    "Fender",
    "Skull Crusher",
    "Fester",
    "Slasher",
    "Fisheye",
    "Steelshot",
    "Flack",
    "Surge",
    "Gargoyle",
    "Sythe",
    "Grave",
    "Trip",
    "Gunner",
    "Trooper",
    "Hash",
    "Tweek",
    "Hashtag",
    "Vein",
    "Indominus",
    "Void",
    "Ironclad",
    "Wardon",
    "Killer",
    "Wraith",
    "Knuckles",
    "Zero",
    "Steel",
    "Kevlar",
    "Lightning",
    "Tito",
    "Bullet-Proof",
    "Fire-Bred",
    "Titanium",
    "Hurricane",
    "Ironsides",
    "Iron-Cut",
    "Tempest",
    "Iron Heart",
    "Steel Forge",
    "Pursuit",
    "Steel Foil",
    "Upsurge",
    "Uprising",
    "Overthrow",
    "Breaker",
    "Sabotage",
    "Dissent",
    "Subversion",
    "Rebellion",
    "Insurgent",
    "Acid Gosling",
    "Admiral Tot",
    "AgentHercules",
    "Airport Hobo",
    "Alley Frog",
    "Alpha",
    "AlphaReturns",
    "Angel",
    "AngelsCreed",
    "Arsenic Coo",
    "AtomicBlastoid",
    "Baby Brown",
    "Back Bett",
    "Bad Bunny",
    "Bearded Angler",
    "Beetle King",
    "Betty Cricket",
    "Bit Sentinel",
    "Bitmap",
    "BlacKitten",
    "Blister",
    "BlisteredOutlaw",
    "Blitz",
    "BloodEater",
    "Bonzai",
    "BoomBeachLuvr",
    "BoomBlaster",
    "BootlegTaximan",
    "Bowie",
    "Bowler",
    "Breadmaker",
    "Broomspun",
    "Buckshot",
    "Bug Blitz",
    "Bug Fire",
    "Bugger",
    "Cabbie",
    "CandyButcher",
    "Capital F",
    "Captain",
    "CelticCharger",
    "Cereal Killer",
    "Chasm Face",
    "Chew Chew",
    "Chicago Blackout",
    "Ballistic",
    "Furore",
    "Uproar",
    "Fury",
    "Ire",
    "Demented",
    "Wrath",
    "Madness",
    "Schizo",
    "Rage",
    "Savage",
    "Manic",
    "Frenzy",
    "Mania",
    "Derange",
    "CobraBite",
    "Cocktail",
    "CommandX",
    "Commando",
    "Congo Wire",
    "Cool Iris",
    "Cool Whip",
    "Cosmo",
    "Crash Override",
    "Crash Test",
    "Crazy Eights",
    "Criss Cross",
    "Cross Thread",
    "Cujo",
    "Cupid Dust",
    "Daffy Girl",
    "Dahlia Bumble",
    "DaisyCraft",
    "Dancing Madman",
    "Dangle",
    "DanimalDaze",
    "Dark Horse",
    "Darkside Orbit",
    "Darling Peacock",
    "Day Hawk",
    "Desert Haze",
    "Desperado",
    "Devil Blade",
    "Devil Chick",
    "Dexter",
    "Diamond Gamer",
    "Digger",
    "Disco Potato",
    "Disco Thunder",
    "DiscoMate",
    "Don Stab",
    "Doz Killer",
    "Dredd",
    "DriftDetector",
    "DriftManiac",
    "Drop Stone",
    "Dropkick",
    "DuckDuck",
    "Earl of Arms",
    "Easy Sweep",
    "Eerie Mizzen",
    "ElactixNova",
    "Elder Pogue",
    "Electric Player",
    "Ember Rope",
    "Esquire",
    "ExoticAlpha",
    "EyeShooter",
    "Fabulous",
    "Fast Draw",
    "FastLane",
    "Father Abbot",
    "FenderBoyXXX",
    "Fennel Dove",
    "Feral Mayhem",
    "Fiend Oblivion",
    "FifthHarmony",
    "Fire Feline",
    "Fire Fish",
    "FireByMisFire",
    "Fist Wizard",
    "Atilla",
    "Darko",
    "Terminator",
    "Conqueror",
    "Mad Max",
    "Siddhartha",
    "Suleiman",
    "TheButcher",
    "Thor",
    "Napoleon",
    "Maximus",
    "Khan",
    "Geronimo",
    "Leon",
    "Leonidas",
    "Dutch",
    "Cyrus",
    "Hannibal",
    "Dux",
    "Mr. Blonde",
    "Agrippa",
    "Jesse James",
    "Matrix",
    "Bleed",
    "X-Skull",
    "Gut",
    "Nail",
    "Jawbone",
    "Socket",
    "Fist",
    "Skeleton",
    "Footslam",
    "Tooth",
    "Craniax",
    "Head-Knocker",
    "K-9",
    "Bone",
    "Razor",
    "Kneecap",
    "Cut",
    "Slaughter",
    "Soleus",
    "Gash",
    "Scalp",
    "Blood",
    "Scab",
    "Torque",
    "Torpedo",
    "Wildcat",
    "Automatic",
    "Cannon",
    "Hellcat",
    "Glock",
    "Mortar",
    "Tomcat",
    "Sniper",
    "Siege",
    "Panther",
    "Carbine",
    "Bullet",
    "Jaguar",
    "Javelin",
    "Aero",
    "Bomber",
    "Howitzer",
    "Albatross",
    "Strike Eagle",
    "Gatling",
    "Arsenal",
    "Rimfire",
    "Avenger",
    "Hornet",
    "Centerfire",
    "Hazzard",
    "Grizzly",
    "Wolverine",
    "Deathstalker",
    "Snake",
    "Wolf",
    "Scorpion",
    "Vulture",
    "Claw",
    "Boomslang",
    "Falcon",
    "Fang",
    "Viper",
    "Ram",
    "Grip",
    "Sting",
    "Boar",
    "Black Mamba",
    "Lash",
    "Tusk",
    "Goshawk",
    "Gnaw",
    "Polar Bee",
    "Poppy Coffee",
    "Poptart AK47",
    "Prometheus",
    "Psycho Thinker",
    "Pusher",
    "Racy Lion",
    "RadioactiveMan",
    "Raid Bucker",
    "Rando Tank",
    "Ranger",
    "Red Combat",
    "Red Rhino",
    "RedFeet",
    "RedFisher",
    "RedMouth",
    "Reed Lady",
    "Reno Monarch",
    "Returns",
    "RevengeOfOmega",
    "Riff Raff",
    "Roadblock",
    "RoarSweetie",
    "Rocky Highway",
    "Roller Turtle",
    "Romance Guppy",
    "Rooster",
    "Rude Sniper",
    "Saint La-Z-Boy",
    "Sandbox",
    "Scare Stone",
    "ScaryNinja",
    "ScaryPumpkin",
    "Scrapper",
    "Scrapple",
    "Screw",
    "Screwtape",
    "Seal Snake",
    "Shadow Bishop",
    "Shadow Chaser",
    "Shooter",
    "ShowMeSunset",
    "ShowMeUrguts",
    "Sienna Princess",
    "Silver Stone",
    "Sir Shove",
    "Skull Crusher",
    "Sky Bully",
    "Sky Herald"
]
